version: "3.9"

services:
  database:
    image: pgvector/pgvector:pg16
    container_name: embed-database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5438:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    image: "migrate/migrate:latest"
    depends_on:
      - database
    volumes:
      - ./db/migrations:/db/migrations
    command: [
      "-path",
      "/db/migrations",
      "-database",
      "postgres://${DB_USER}:${DB_PASSWORD}@database:5432/${DB_NAME}?sslmode=${DB_SSLMODE}",
      "up"
    ]

  service:
    build: .
    container_name: embed-service
    depends_on:
      - database
      - migrate
    env_file:
      - .env
    ports:
      - "8080:8080"


volumes:
  pgdata:
